# Generated by Django 3.0 on 2020-03-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame_content',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='frame_title',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sort_detail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
