# Generated by Django 3.0 on 2020-03-26 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thinkapp', '0002_auto_20200327_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame_content',
            old_name='Frame_title_id',
            new_name='Frame_title',
        ),
        migrations.RenameField(
            model_name='frame_title',
            old_name='Sort_id',
            new_name='Sort',
        ),
    ]
