# Generated by Django 3.0 on 2020-03-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkapp', '0003_auto_20200327_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame_content',
            name='sub_title',
            field=models.IntegerField(default='1', verbose_name='0，子标题没有输入；1，有输入'),
        ),
    ]
