# Generated by Django 3.0 on 2020-04-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True, verbose_name='主题')),
                ('contact', models.CharField(max_length=64, null=True, verbose_name='联系方式')),
                ('content', models.CharField(max_length=200, null=True, verbose_name='联系方式')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
